### Get all items
GET http://127.0.0.1:8000/api/cart/ HTTP/1.1
Authorization: Bearer 

### Post item
POST http://127.0.0.1:8000/api/cart/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "item": 1,
    "quantity": 1
}

### Get cart from user
GET http://127.0.0.1:8000/api/usercart/ HTTP/1.1
Authorization: Bearer 
Content-Type: application/json
